config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cards
  get 'tags/:tag', to: 'cards#index', as: :tag
  get 'tests/:tag', to: 'cards#test_tag', as: :test_tag
  get 'test/:filter', to: 'cards#test_frequence', as: :test_frequence
  get 'test_index', to: 'cards#test_index', as: :test_index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :question, presence: true
  validates :answer, presence: true, unless: ->(card){card.picture.present?}
  validates :picture, presence: true, unless: ->(card){card.answer.present?}
  default_scope -> { order(created_at: :desc) }

  validates :tag_list, presence: true
  acts_as_taggable
  validates :frequence, inclusion: { in: %w(plus moyen moins), message: "%{value} n'est pas une fréquence valide" }
  mount_uploader :picture, PictureUploader
  validate :picture_size_validation, :if => "picture?"  
  validates_attachment_presence :datafile unless :datafile

  belongs_to :user


  private
    def picture_size_validation
      errors[:picture] << "Photo attachée doit être inférieure à 2MB, ici #{picture.size}" if picture.size > 2.megabytes
    end

      # Validates the size of an uploaded picture.
      # def picture_size
      #   if picture.size > 2.megabytes
      #     errors.add(:picture, "should be less than 2MB")
      #   end
      # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :cards

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private

    def after_sign_in_path_for(resource)
      cards_path
    end

    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(user)
      root_path
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'will_paginate/array' 
  before_action :find_card, only:[:edit, :destroy, :show, :update]

  def new
    @card = Card.new
    @cards = current_user.cards

  end

  def create
    @card = Card.new(card_params)
    @card.user = current_user
    if @card.save
      flash[:success] = "Carte créée"
      redirect_to cards_path
    else
      render 'new'
    end
  end

  def index
    if params[:tag]
      @cards = current_user.cards.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
      else
        @cards = current_user.cards.paginate(page: params[:page], per_page: 10)
    end
    @cards_total = current_user.cards
  end


  def test_index
    @cards_total = current_user.cards
    @cards = current_user.cards
    if params[:tag]
      @cards = current_user.cards.tagged_with(params[:tag])
      @cards = @cards.paginate
    end

  end

  def test_tag

    @cards = current_user.cards.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 1)
    @card = @cards.sample

    if params[:page].nil?
      @count = 1
    else
      @count = params[:page]
    end

  end

  def test_frequence

    @cards = current_user.cards.paginate(page: params[:page], per_page: 3)
    if params[:filter]
    @cards = current_user.cards.select { |card| card[:frequence] == params[:filter] }
    @cards = @cards.paginate(page: params[:page], per_page: 3)
  end
    @card = @cards.sample

    if params[:page].nil?
      @count = 1
    else
      @count = params[:page]
    end

  end


  def test
    if params[:tag]
      @cards = current_user.cards.tagged_with(params[:tag])
    else
      @cards = current_user.cards.paginate(page: params[:page], per_page: 1)
      @card = @cards.sample  
    end
  end

  def show

  end

  def edit
    @cards = current_user.cards
    
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to :back
    
  end

  private

  def card_params
    params.require(:card).permit(:question, :answer, :frequence, :tag_list, :picture)
  end

  def find_card
    @card = Card.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Modifier la carte</h1>
      <%= render 'shared/error_messages' %>
      <%= simple_form_for @card, html: {multipart: true} do |f| %>
        <%= f.input :question %>
        <%= f.input :answer %>

        <% if @card.picture? %>
        <h3>image choisie</h3>
          <%= image_tag @card.picture.url %>
          <% end %>

        <%= f.file_field :picture, class:'btn-orange', accept: 'image/jpeg,image/gif,image/png' %>
        <%= f.label :tag, label: 'Catégorie' %>
        <!-- <p>Catégories existantes:</p> -->
        <% if @cards%>
          <span><i>Déja créées</i></span>
          <span><% @cards.tag_counts.each do |tag| %>
            <%= tag %>
          <% end %>
          </span>
        <% end %>
        
        <%= f.text_field :tag_list, class: "form-control" %>
        <%= f.input :frequence, collection: ['plus', 'moyen', 'moins'], prompt: 'Choisssez une récurrence' %>
        <%= f.button :submit, class:"btn-orange round-green-btn" %>
      <% end %>    
    <div class="text-center space-updown">
          <%= link_to cards_path,class:'btn-green round-green-btn' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>

        </div>
    </div>  
  </div>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 2) {
      alert('Maximum file size is 2MB. Please choose a smaller file.');
    }
  });
</script>

app/views/cards/index.html.erb
<div class="container" id="home-index">
  <% if notice || alert %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>    
  <% end %>
<div id="title" class="text-center hidden-xs"><h1>My ANKI</h1>
  <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %>
</div>

<div class="panel hidden-xs" id="left-container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <ul class="list-vertical">
        <li><%= link_to new_card_path,class:'btn-orange round-green-btn' do %><span class="fa fa-plus-square fa-1x"></span> Carte <% end %></li>
        <li><%= link_to '/test_index',class:'btn-green round-green-btn' do %><span class="fa fa-graduation-cap fa-1x"></span> Tests <% end %></li>
        <li><%= link_to cards_path ,class:'delete btn-red round-green-btn' do %><span class="fa fa-home fa-1x"></span> <% end %></li>

        <li><i class="fa fa-battery-full" aria-hidden="true"></i>
          <%= @cards_total.length %> cartes !</li>
            <div id="cat-block">
              <h4>Mes catégories</h4>
            <% if @cards %>
              <% tag_cloud @cards_total.tag_counts, %w[s m l] do |tag, css_class| %>
              <li><i class="fa fa-puzzle-piece" aria-hidden="true"></i><%= link_to tag.name, tag_path(tag.name), class:'index-tag css_class all-btn cat-block' %>
              </li>
              <hr class="hr-red text-center">
              <% end %>  
            <% end %>
            </div> <!-- cat-block -->
              
      </ul>
    </div>  
  </div>
</div> <!-- id left-container -->
  
<div class="panel hidden-xs" id="right-container">
  <div class="row">
    <div class="col-xs-12">
       <!-- card-cat -->
    </div>
      <div class="col-xs-12">
        <% if @cards %>
        <div class="hidden-xs">

              <% @cards.each do |card| %>
              <div class="row question-block">
                <div class="col-sm-8 question-details">
                    <h4><i class="fa fa-question-circle-o" aria-hidden="true"></i>
                    <%= link_to card.question, card_path(card) %></h4>
                    <span class="index-tag"><%= raw card.tag_list.map { |t| t }.join (', ' )if card.tag_list != [] %></span>
                    <span class="index-tag"><%= card.frequence %></span>
                </div>
                <div class="col-sm-4 index-icons">
                  <div class="question-ctrls pull-right">
                    <%= link_to edit_card_path(card),class:'index-btns modify space-right-left-sm' do %><span class="fa fa-pencil fa-2x modify"></span><% end %>
                    <%= link_to card_path(card), method: :delete,class:'index-btns delete space-right-left-sm' do %><span class="fa fa-trash-o fa-2x delete"></span> <% end %>  
                  </div>    
                </div>
              </div>
              <hr>
            <% end %> <!-- each do card -->
            <div class="pull-right hidden-xs">
              <%= will_paginate @cards , renderer: BootstrapPagination::Rails %>    
            </div>

            
      </div> <!-- hiden xs -->
        </div> <!-- col xs 12 -->
        <% end %>
    </div>
  </div> <!-- row -->
</div> <!-- panel right-cntr -->

  <div class="clear hidden-xs">
  </div>
  <%= render 'shared/phone_layout' %>

</div>

app/views/cards/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Nouvelle carte</h1>
      <%= render 'shared/error_messages' %>
      <%= simple_form_for @card, html: {multipart: true} do |f| %>
        <%= f.input :question, label: 'Question' %>
        <p><i>Ajoutez une réponse OU une image</i></p>
        <%= f.input :answer, label: 'Réponse' %>
        <%= f.file_field :picture, class:'btn-orange', accept: 'image/jpeg,image/gif,image/png' %>

        <br>
        <%= f.label :tag, label: 'Catégorie' %>
        
        <!-- <p>Catégories existantes:</p> -->
        <% if @cards%>
          <span><i>Déja créées</i></span>
          <span><% @cards.tag_counts.each do |tag| %>
            <%= tag %>
          <% end %>
          </span>
        <% end %>
        
        <%= f.text_field :tag_list, class: "form-control" %>
        <%= f.input :frequence, label: 'Fréquence', collection: ['plus', 'moyen', 'moins'], prompt: 'Choisissez une récurrence' %>
        <%= f.button :submit, class:"btn-orange round-green-btn"%>
      <% end %>    
    <div class="text-center space-updown">
          <%= link_to cards_path,class:'btn-green round-green-btn' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>

        </div>
    </div>  
  </div>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 2) {
      alert('Maximum file size is 2MB. Please choose a smaller file.');
    }
  });
</script>

app/views/cards/show.html.erb
<div class="container">
  <h2><%=@card.question %></h2>
  <% if @card.picture? %>
    <%= image_tag @card.picture.url %>
    <% else %>
    <p><%= @card.answer %></p>
  <%end %>
</div>

app/views/cards/tag.erb
<h1>Cards of a tag</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <div class="col-xs-12">
          <% if @cards %>
          <div class="hidden-xs">

                <% @cards.each do |card| %>
                <div class="row question-block">
                  <div class="col-sm-8 question-details">
                      <h4><i class="fa fa-question-circle-o" aria-hidden="true"></i>
                      <%= link_to card.question, card_path(card) %></h4>
                      <span class="index-tag"><%= raw card.tag_list.map { |t| t }.join (', ' )if card.tag_list != [] %></span>
                      <span class="index-tag"><%= card.frequence %></span>
                  </div>
                  <div class="col-sm-4 index-icons">
                    <div class="question-ctrls pull-right">
                      <%= link_to edit_card_path(card),class:'index-btns modify space-right-left-sm' do %><span class="fa fa-pencil fa-2x modify"></span><% end %>
                      <%= link_to card_path(card), method: :delete,class:'index-btns delete space-right-left-sm' do %><span class="fa fa-trash-o fa-2x delete"></span> <% end %>  
                    </div>    
                  </div>
                </div>
                <hr>
              <% end %> <!-- each do card -->
              <div class="pull-right hidden-xs">
                <%= will_paginate @cards , renderer: BootstrapPagination::Rails %>    
              </div>

              
        </div> <!-- hiden xs -->
          </div> <!-- col xs 12 -->
          <% end %>
      </div>

      </div>  
    </div>

  <div class="text-center space-updown">
    <%= link_to cards_path,class:'btn-green' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>

  </div>
</div>

app/views/cards/test.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h1>Le test</h1>
      <div id="question">
        <%= @card.question %>  
      </div>
      <p><%= @card.tag_list %></p>
      
      <br>

          <br>
          <label for="answer"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></label>
          <input type=radio id="answer" name="group">
          <span id="content"><%= @card.answer %></span>
          <br>

          <%= will_paginate @cards , renderer: BootstrapPagination::Rails %>    
    </div>
  </div>
  <div class="text-center">
    <%= link_to "Revenir à l'acceuil", cards_path, class:'btn btn-primary' %>
  </div>
</div>

app/views/cards/test_frequence.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <% if @card %>
            <h1>Le test de la récurrence <%=params[:filter] %></h1>
            <div id="question">
                <%= @card.question %>
                <p><%= @count %> / <%= @cards.count %></p>  
            </div>
              <br>
                <label for="answer"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></label>
                <input type=radio id="answer" name="group">
                <span id="content">
                <% if @card.picture? %>
                  <%= image_tag @card.picture.url %>
                  <% else %>
                  <%= @card.answer %>
                <% end %>
                </span>
                
                <br>
                  <%= will_paginate @cards, renderer: BootstrapPagination::Rails, :page_links => false %>    
          </div>

        </div>
        <div class="text-center space-updown">
          <%= link_to cards_path,class:'btn-green' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>

        </div>
      <% else %>
        <h2>Tu n'as pas encore ajouté de cartes.</h2>
        <p><%= link_to "Clique-ici", new_card_path %> pour démarrer</p>
        <div class="text-center space-updown">
          <%= link_to cards_path,class:'btn-green' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>
      <% end %>

      
</div>

app/views/cards/test_index.html.erb
<div class="container">
  <% if @cards %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <div id="test-index">
        <h1>Se tester </h1>
        <div class="panel">
          <h2>Par catégorie</h2>
            <div class="test-index-panel">
                  <% tag_cloud @cards_total.tag_counts, %w[s m l] do |tag, css_class| %>
                    <%= link_to test_tag_path(tag.name), class:'btn-blue-small' do %><span class="fa fa-tag fa-1x"></span> <%= tag.name %> <% end %> 
                  <% end %>    
                
            </div>  
            
        </div>
          
        <div class="panel">
          <h2>Par récurrence</h2>
          <div class="test-index-panel">
            <% Card.unscoped.all.select("DISTINCT(FREQUENCE)").each do |card| %>
            <%= link_to test_frequence_path(card.frequence),class:'btn-orange' do %><span class="fa fa-calendar fa-1x"></span> <%= card.frequence %> <% end %>
            <% end %>  
          </div>
            
        </div>
        
      
    </div>
    <div class="text-center space-updown">
      <%= link_to cards_path,class:'btn-green all-btn' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>

    </div>
  </div>
    
  </div>
  <% end %>

</div>

app/views/cards/test_tag.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h2>Le test <%= @card.tag_list %> </h2>
      <div id="question">
        <%= @card.question %>
        <p><%= @count %> / <%= @cards.count %></p>  
      </div>
      <br>
          <label for="answer"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></label>
          <input type=radio id="answer" name="group">
          <span id="content">
            <% if @card.picture? %>
              <%= image_tag @card.picture.url %>
              <% else %>
              <%= @card.answer %>
            <% end %>
          </span>
          <br>

          <%= will_paginate @cards, renderer: BootstrapPagination::Rails, :page_links => false %>    
    </div>
  </div>
  <div class="text-center space-updown">
    <%= link_to cards_path,class:'btn-green' do %><span class="fa fa-arrow-right fa-1x"></span> Accueil <% end %>
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>My A.N.K.I</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- Réalisé par Mathieu Chiron, s123567@github.com -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<body class="landing-page">
  <div class="container" id="landing">


        <div id="hero" class="center-block">
          <%= image_tag "brain-puzzle.jpg", size:"300x300", class:'img-circle img-responsive' %>
        </div>  


        <div id="welcome-form" class="home-white-form">
          <div class="round-green-btns text-center">
              <h4><%= link_to 'Inscription', new_user_registration_path, class:'round-green-btn signup' %></h4>
            <hr>
              <h4><%= link_to 'Connexion', new_user_session_path, class:'round-green-btn' %></h4>
              <hr>
              <p><%= link_to 'Plus de détails sur ANKI', 'https://fr.wikipedia.org/wiki/R%C3%A9p%C3%A9tition_espac%C3%A9e', :target => '_blank', class:"round-green-btn" %></p>
              <p class="round-green-btn">A propos</p>
              <% if notice || alert %>
              <p class="notice delete"><%= notice %></p>
              <p class="alert delete"><%= alert %></p>    
              <% end %>
          </div>
            
          
        </div>


      
      
  </div>


  
</body>

app/views/shared/_error_messages.html.erb
<% if @card && @card.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@card.errors.count, "error") %>.
      </div>
      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_navbar-mobile.html.erb
<div class="hidden-xs">
  <nav class="navbar navbar-default hidden-sm-up">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MY ANKI</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Ajouter une carte", new_card_path %></li>
        <li><a href="/test_index">Faire un test</a></li>
        <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/shared/_phone_layout.html.erb
<% if @cards %>
  <div class="visible-xs">
    <div class="navbar-mobile inline">
      <li><%= link_to cards_path ,class:'delete btn-red round-green-btn' do %><span class="fa fa-home fa-1x"></span> <% end %></li>
      <li><%= link_to new_card_path,class:'btn-orange round-green-btn' do %><span class="fa fa-plus-square fa-1x"></span> Carte <% end %></li>
      <li><%= link_to '/test_index',class:'btn-green round-green-btn' do %><span class="fa fa-graduation-cap fa-1x"></span> Tests <% end %></li>

      <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class:'round-green-btn' %></li>
    </div>
        
        <div class="row">
          <% @cards.each do |card| %>
          <div class="col-xs-12">
            <div class="space-updown space-left-right panel-mobile">
              <h3><i class="fa fa-question-circle space-right-left-sm" aria-hidden="true"></i><%= card.question %></h3>
            </div> <!-- panel-mobile -->

            <div class="controls center-block">
              <div class="controls-left pull-left btn-orange-small">
                <h4><span class="fa fa-tag fa-1x space-right-left-sm"></span><%= raw card.tag_list.map { |t| t }.join (', ' ) if card.tag_list != [] %><span class="fa fa-calendar fa-1x space-right-left-sm"></span><%= card.frequence %></h4>
              </div>
              <div class="controls-right pull-right">
                <%= link_to edit_card_path(card),class:'space-right-left' do %><span class="fa fa-pencil fa-2x modify"></span> <% end %>
                <%= link_to card_path(card), method: :delete,class:'space-right-left' do %><span class="fa fa-trash-o fa-2x delete"></span> <% end %>
              </div>  
            </div> <!-- controls -->
          </div>
        <% end %>
      </div>
      <div class="text-center">
        <%= will_paginate @cards , renderer: BootstrapPagination::Rails %>    
      </div>
  </div> <!-- visible xs -->
  <% end %>